name: Test, Lint, Build and Deploy on Github Pages

on:
  push:
    branches: ["master", "main"]

  # Позволяет запустить этот рабочий процесс вручную на вкладке Actions
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Устанавливаем зависимости
      - name: Install dependencies
        run: npm install

      # Запускаем тесты и линтер
      - name: Run tests and linter
        run: npm run lint && npm test

      # Собираем приложение
      - name: Build Application
        run: npm run build

      # Собираем Storybook
      - name: Build Storybook
        run: npm run build-storybook

      # Объединяем приложение и Storybook для развертывания
      - name: Prepare deployment folder
        run: |
          # Создаем папку storybook внутри dist
          mkdir -p dist/storybook
          # Копируем содержимое storybook-static в dist/storybook
          cp -r storybook-static/* dist/storybook/

      # Публикуем объединенное приложение и Storybook на Github Pages
      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.2.1
        with:
          branch: gh-pages
          folder: dist
          commit-message: "Automatically publish App and Storybook"

      # Останавливаем выполнение строго при неудачных тестах
      - name: Fail on failed tests
        run: |
          if [ ${{ job.status }} == 'failure' ]; then exit 1; fi;
